# Generated by Django 4.2.8 on 2023-12-11 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='classe',
            field=models.CharField(choices=[('Econômica', 'Econômica'), ('Executiva', 'Executiva')], max_length=20),
        ),
        migrations.AlterField(
            model_name='voo',
            name='data_partida',
            field=models.CharField(default='12-12-2023', max_length=10),
        ),
        migrations.AlterField(
            model_name='voo',
            name='numero_voo',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999, message='O número do voo deve ter no máximo 4 dígitos.'), django.core.validators.MinValueValidator(1, message='O número do voo deve ter exatamente 4 dígitos.')]),
        ),
    ]
